#!/usr/bin/env  bash



VERSION='$Id: general.template.sh,v 1.2 2012/04/14 04:19:45 dallas Exp dallas $'  ;
USAGE="${0##*/}  [ -h | -v ]  [-d]  <hpodder stuff here>"  ;

#  renice   +86   ${$}  ;

source ~/bin/security.pack  ;



# Help subsystem #######################################

function help_message ()
{
  cat <<HELP_MESSAGE  ;

  ${USAGE}

  -h                Help
  -v                Version
  -d                Debug
  
  run 'hpodder -h'  to get details on the switches of the real hpodder command.
  This is just a wrapper to try and help action when running hpodder with 
  torsocks.

HELP_MESSAGE

  exit  ;
} ;

function  help_check  ()
{

[ -f "${1}" ]  &&  return  ;
#             - continue, return to execution if $1 is a file


case  ${1}  in

[-/][hH?]* | --[hH]* )
  help_message  ;
  ;;

[-/][vV]* | --[vV]* )
  echo ${VERSION#\$Id\: }  ;
  exit  ;
  ;;

[-/][dD]* | --[dD]* )
  SCRIPTDEBUG='1'  ;
  shopt -s extdebug  ;
  shift  1  ;
  ;;


*@* )
  :  ;
  ;;

* )
  : help_message
  ;;

esac  ;

}  

help_check   "${1}"  ;


##  Process  Parameters  #######################################3


while getopts ':ip:'  SWITCHES
do
  # leading  ':' or OPTERR=0 turns off weird error message
  #  for invalid options

#       TODO:   '--'  end of switches

  case  "${SWITCHES}"  in
  \? ) echo ${USAGE} ; 
      exit    ;
      ;;
#    p ) MPARMS="${OPTARG}"  ;
#        MPARMS="${MPARMS#=}"  ;
#        #  echo "case: ${OPTARG}"  ;
#        ;;
  * )   :  ;
      ;;
  esac
done

shift  $(( ${OPTIND}  -  1 ))
#  --  a piece of boilerplate to sweep options out of the way
#      typically leaving file names


##  Globals, Aliases, Functions  etc. #############################

function  d2x  ()
{
  RESULT=$( bc <<< "ibase=10;obase=16;${1}"    \
      |  tr '[:upper:]'  '[:lower:]'   )  ; 
}

function  right  ()
{
  RESULT="${1}"  ;
  LENGTH="${2}"  ;
  PAD="${3:-' '}"  ;
  while  (( ${#RESULT} < LENGTH ))
  do
    RESULT="${PAD}${RESULT}"  ;
  done  ;
}


#  shopt -s expand_aliases   ;

#  real, old:
#  UA='Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)'
#  current, real:
#  UA='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.6 (KHTML, like Gecko) Chrome/20.0.1092.0 Safari/536.6'
#  unreal:
#  UA='Mozilla/9.0 (Windows NT 9.1; WOW64) AppleWebKit/936.6 (KHTML, like Gecko) Chrome/21.0.1092.0 Safari/936.6'



function    torchk  ()
  {
  torcnt=$( ps  auxwww | grep '[/]usr/bin/tor'  )  ;
  if ((   torcnt < 1 ))
    then
    echo 'Tor does not seem to be running, exiting script.'  ;
    echo 'You might try '  ;
    echo '   "# sudo service tor start" or'        ;
    echo '   "# /etc/init.d/tor start" '
    echo '   to get it running.'  ;
    exit  ;
    fi  ;
  }

##  MAIN BODY  #################################################



torchk  ;

source   /usr/bin/torsocks   on       ;

export   LD_PRELOAD   ;


exec  hpodder    "${@}"         ;
