ln -s ~/Linux-Scripts/Chime/chime-startup.sh            ~/chime-startup.sh
ln -s ~/Linux-Scripts/Chime/mount-bell.sh               ~/mount-bell.sh
ln -s ~/Linux-Scripts/Chime/tty-script.sh               ~/tty-script.sh
ln -s ~/Linux-Scripts/Chime/unmount-bell.sh             ~/unmount-bell.sh
ln -s ~/Linux-Scripts/Chime/Old-Scripts/cap             ~/cap
ln -s ~/Linux-Scripts/Chime/Old-Scripts/homepage.sh     ~/homepage.sh
ln -s ~/Linux-Scripts/Chime/Old-Scripts/inflection.sh   ~/inflection.sh
ln -s ~/Linux-Scripts/Chime/Old-Scripts/jjs             ~/jjs
ln -s ~/Linux-Scripts/Chime/Old-Scripts/rn              ~/rn
ln -s ~/Linux-Scripts/Chime/Old-Scripts/space2dash      ~/space2dash
ln -s ~/Linux-Scripts/Chime/Old-Scripts/strm2mp3        ~/strm2mp3
ln -s ~/Linux-Scripts/Chime/Old-Scripts/thpodder        ~/thpodder
ln -s ~/Linux-Scripts/Chime/Old-Scripts/weather.sh      ~/weather.sh
ln -s ~/Linux-Scripts/Chime/Old-Scripts/wx              ~/wx
